#!/bin/bash

if [ $# -eq 4 ]; then

  instance="${1}"
  virtualhost="${2}"
  url="${3}"

  #
  # Handle calendar locations
  
  # find /etc/device/services/mail/calendar/ -mindepth 1 -maxdepth 1 -type l
  while read line; do

    if test ! -f "$line/virtualhost.d/listen.d/instance.d/name.txt" -o "${instance}" != "$(head -n 1 $line/virtualhost.d/listen.d/instance.d/name.txt)"; then
      continue;
    fi
    if test ! -f "$line/virtualhost.d/name.txt" -o "${virtualhost}" != "$(head -n 1 $line/virtualhost.d/name.txt)"; then
      continue;
    fi

    # read in the path if present
    path="/calendar"
    if test -f "${line}/path.txt"; then
      path="$(head ${line}/path.txt)"
    fi
    # empty path becomes a /
    if test -z "${path}";then
      path="/"
    fi

    echo
    echo "    Calendar:"
    echo "      url: ${url}${path}"

  done < <(find /etc/device/services/mail/calendar/ -mindepth 1 -maxdepth 1 -type l)

fi


